### ISSUE TITLE
Improve visual togetherness for substitution-collection 

### ISSUE THREAD

**Issue by SpyrexDE** [Antricks/substitution-table#24]
Current visual appearance:
<samp>All entries have round corners, no shadow</samp>
<img width=300 src="https://user-images.githubusercontent.com/57133330/143765110-f3c64277-f6ae-4e69-96b9-3b01dda1aef4.png"/>

Suggestion:
<samp>Only the outer entries have round corners, the collection has a smooth light shadow</samp>
<img width=300 src="https://user-images.githubusercontent.com/57133330/143765127-90d28f32-87d2-4e74-a1d6-e951f8311624.png"/>

**Comment by Antricks** [comment]
Have you already written CSS for that? If so, feel free to push it. Actually, I initially wanted to do exactly that too.

**Comment by SpyrexDE** [comment]
> Have you already written CSS for that?

Well, just prototyped in the developer tools.
If you have enough time you could try to fully implement this.

**Comment by Antricks** [comment]
Are you happy with how it looks now?

**Comment by SpyrexDE** [comment]
I thought about a more smooth and evenly shadow like in the screenshot, but that's also okay. But maybe also add a shadow to the navbar.

**Comment by Antricks** [comment]
With the latest commit, the shadows are softer now and there's a shadow below the navbar. If there's nothing else left, I'd like to close this issue then.
