### ISSUE TITLE
Add Caching

### ISSUE THREAD

**Issue by SpyrexDE** [Antricks/substitution-table#6]
Without caching the user experience will decrease a lot, due to relatively long loading times.
I suggest to always cache one day before and two days after the currently shown day.

**Comment by Antricks** [comment]
Is that what you imagined?

**Comment by Antricks** [comment]
We now pre-load a day before and after and refresh data when it gets older than 2 minutes. Is this okay?

**Comment by SpyrexDE** [comment]
Sounds good.
